services:
  mysql:
    image: mariadb:10.6
    restart: always
    container_name: ctr_table_laravel_mysql
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - vol_table_laravel:/var/lib/mysql
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    networks:
      - net_table_laravel

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    container_name: ctr_table_laravel_phpmyadmin
    ports:
      - "${PMY_EXTERNAL_PORT}:${PMY_PORT}"
    environment:
      - TZ=${TZ}
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    networks:
      - net_table_laravel

  table-laravel:
    build:
      context: ./table-laravel
      dockerfile: DockerFile
    image: img_table_laravel:1.0
    restart: always
    container_name: ctr_table_laravel
    depends_on:
      - mysql
    environment:
      - APP_NAME="${APP_NAME}"
      - TZ=${TZ}
      - APP_URL=${APP_URL}
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./table-laravel:/var/www/html:rw
    ports:
      - "8000:80"
    networks:
      - net_table_laravel
    command: /bin/bash -c "if [ ! -d vendor ]; then composer install; fi && apache2-foreground"

volumes:
  vol_table_laravel:
    name: vol_table_laravel

networks:
  net_table_laravel:
    name: net_table_laravel
    driver: bridge
